import * as yup from 'yup';

export const validationSchemaFormular = yup.object({
  finanzierungszweck: yup.string().required(),
  immobilientyp: yup.string().required(),
  nutzung: yup.string().required(),
  standort_plz: yup.string().required(),
  bundesland: yup.string().required(),
  haushaltseinkommen: yup.string().required(),
  schufa: yup.string().required(),
  kaufpreis: yup.string().required(),
  immobilienbesitz: yup.string().required(),
  anrede: yup.string().required(),
  titel: yup.string(),
  vorname: yup.string().required(),
  name: yup.string().required(),
  geburtsdatum: yup.string().required(),
  strasse: yup.string().required(),
  hausnummer: yup.string(),
  familienstand: yup.string().required(),
  staatsangehorigkeit: yup.string().required(),
  plz: yup.string().required(),
  ort: yup.string().required(),
  telefon: yup.string().required(),
  email: yup.string().email().required(),
  erreichbarkeit: yup.string().required(),
  berufsstatus: yup.string().required(),
  bemerkung: yup.string().default(''),
  videoberatung: yup.string().required(),
  newsletter: yup.boolean().required(),
  agb: yup.boolean().required(),
});

export const validationSchemaKontakt = yup.object({
  anrede: yup.string(),
  vorname: yup.string().required(),
  name: yup.string().required(),
  strasse: yup.string().required(),
  hausnummer: yup.string(),
  plz: yup.string().required(),
  ort: yup.string().required(),
  telefon: yup.string().required(),
  email: yup.string().email().required(),
  bemerkung: yup.string().default(''),
  agb: yup.boolean().required(),
});
